<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
	pageEncoding="ISO-8859-1"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<title>Masterpass v7 PCI</title>
<style type="text/css">
h2 {
	font-family: Calibri, Candara, Segoe, "Segoe UI", Optima, Arial, sans-serif;
	font-size: 24px;
	font-style: normal;
	font-variant: normal;
	font-weight: 500;
	line-height: 26.4px;
}
div {
    width: 600px;
    border: 1px solid grey;
    border-radius: 5px;
}
</style>
</head>
<body>


	<br><br><br><br>
	<center>
	<div style="text-align: center">

		<h2>v7 Standard Checkout<br><br></h2>

		<!-- <script type="text/javascript" src="https://sandbox.masterpass.com/integration/merchant.js"></script> -->
			
		<script type="text/javascript" src="https://masterpass.com/integration/merchant.js"></script>
			
		<a href="#" onClick="launchUI()"> 
			<img src="https://www.mastercard.com/mc_us/wallet/img/en/US/mcpp_wllt_btn_chk_147x034px.png" />
		</a>
		
		<br><br>
	</div>
	</center>



	<script type="text/javascript">
		function launchUI() {// merchant configuration parameters 
	
			masterpass.checkout({
		        "checkoutId": "bdfb8d5859b2460fbffb63b7ebfd1a92",                                   // Merchant checkout identifier received when merchant onboarded for masterpass
		        "allowedCardTypes": ["master,amex,diners,discover,jcb,maestro,visa"],               // Card types accepted by merchant
		        "amount": "789.53",                                                                 // Shopping cart subtotal
		        "currency": "USD",                                                                  // Currency code for cart
		        "shippingLocationProfile": "US,AU,BE",                                              // Shipping locations supported by merchant - configured in merchant portal
		        "suppress3Ds": false,                                                               // Set true when 3DS not mandatory for the spcecific country
		        "suppressShippingAddress": false,                                                   // Set true when cart items has digital goods only
		        "cartId": "6a7804b7-6e6f-4ec3-ac1c-f79517040829",                                    // Unique identifier for cart generated by merchant
		        "cvc2Support" : true
			});
		}
	</script>
</body>
</html>
